image: 'node:12'

before_script:
  - echo ${CI_JOB_TOKEN}
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.mitre.org/mathompson/ihsus.git
  # - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.mitre.org/mathompson/ihsus.git”.insteadOf git@gitlab.mitre.org:mathompson/ihsus.git
  - npm install
  - which node

test_suite:
  tags:
    - gofsh
  script:
    - npm test
