image: 'node:12'

before_script:
  # - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.mitre.org/mathompson/ihsus.git
  # - cd ihsus
  - npm install
  - which node

test_suite:
  tags:
    - gofsh
  script:
    - npm test
